# Generated by Django 5.0.1 on 2024-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='877648357524', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
