# Generated by Django 4.2.9 on 2024-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='813883003879', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
