# Generated by Django 4.2.9 on 2024-02-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_ver_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='404846164249', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
