# Generated by Django 5.0 on 2023-12-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(verbose_name='дата оплаты')),
                ('amount_payment', models.PositiveIntegerField(blank='True', null='True', verbose_name='сумма оплаты')),
                ('method_payment', models.CharField(choices=[('cash', 'наличные'), ('card', 'перевод')], max_length=20, verbose_name='способ оплаты')),
                ('paid_course', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.lesson', verbose_name='оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
