# Generated by Django 4.2.9 on 2024-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateField(auto_now_add=True, null='True', verbose_name='дата оплаты'),
        ),
    ]
