# Generated by Django 4.2.9 on 2024-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_date_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank='True', max_length=300, null='True', verbose_name='stripe_id'),
            preserve_default='True',
        ),
    ]
