# Generated by Django 5.0 on 2023-12-24 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_course', models.CharField(max_length=50, verbose_name='название курса')),
                ('image_course', models.ImageField(blank='True', null='True', upload_to='course/', verbose_name='картинка курса')),
                ('description_course', models.TextField(verbose_name='описание курса')),
                ('author', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lesson', models.CharField(max_length=50, verbose_name='название урока')),
                ('description_lesson', models.TextField(verbose_name='описание урока')),
                ('image_lesson', models.ImageField(blank='True', null='True', upload_to='lesson/', verbose_name='картинка урока')),
                ('url_lesson', models.URLField(blank='True', null='True', verbose_name='ссылка на видео')),
                ('author', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('url_course', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='ссылка на курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
